### ISSUE TITLE
can i use it?

### ISSUE THREAD

**Issue by PrinzFritz** [cybersonic/extension-cache-redis#1]
Hi Mark, is this extension ready to use in lucee? i have tryed to upload and had read this---> "There is no config.xml file available in the extension!"

**Comment by cybersonic** [comment]
Hi there, it kinda is... I just have to commit stuff. Will look for it and put it up to date. 
There are no functional changes, just bringing it in-line with lucee

**Comment by cybersonic** [comment]
I have uploaded the .lex files 

Give this a try and let me know how you get on! 
https://github.com/cybersonic/extension-cache-redis/blob/master/dist/modern/redisdb-extension-1.0.0.20.lex
